### ISSUE TITLE
[Roadmap]: Reasoning Agenet after V0.6

### ISSUE THREAD

**Issue by BabyCNM** [ag2ai/ag2#246]
### Is your feature request related to a problem? Please describe.

- [] Async Client Call: parallelize LLM calling to speed up searching
- [] Swarm Agent implementation
- [] Efficient Mode: merging thinker and grader
- [] Batch Norm: normalizing scores for MCTS
- [] Multi-round interaction with the Reasoning Agent, with default AssistantAgent system message.

**Comment by Hk669** [comment]
https://github.com/ag2ai/ag2/pull/293

added simple bench.

**Comment by AgentGenie** [comment]
@BabyCNM What is "Add RAG compatibility with the ReasoningAgent" about? I am actually thinking to add reasoning agent to RAG pipeline.

**Comment by giorgossideris** [comment]
Hello @BabyCNM @Hk669 can I help somehow with this issue? I would be happy to assist.

**Comment by marklysze** [comment]
@BabyCNM closing this for now, please reopen if you're able to continue working on it. Thanks!
