### ISSUE TITLE
[Docs] Fixes and improvements across pages

### ISSUE THREAD

**Issue by harishmohanraj** [ag2ai/ag2#280]
### Describe the issue

This issue addresses multiple improvements and bug fixes across the website, including:

- [x] Fix callout boxes across all pages - @KadirCanTufek
- [x] Implement automatic addition of author information to all blog pages - @harishmohanraj - PR#297
- [x] Update headers in the API reference to use lowercase letters.- @harishmohanraj  - PR#297
- [x] Docs generation for `/notebook/agentchat_graph_rag_neo4j.ipynb` is failing- @harishmohanraj - PR#317
- [x] Remove escaped characters (e.g., /{, /<) from the API reference documentation - @harishmohanraj - PR#317
- [x] Fix the javascript console errors - @harishmohanraj - PR#318
- [x] Remove unused Docusaurus-related files from the project - @harishmohanraj - PR#318
- [x] Fix image display issues in the application gallery that occur in production but not locally (3 hr) - @harishmohanraj - PR#319
- [ ] Resolve tag filtering issues in the application gallery and notebook examples pages that work locally but not in production. (4 hr)
