### ISSUE TITLE
[Roadmap Issue]: Documentation Improvement

### ISSUE THREAD

**Issue by sonichi** [ag2ai/ag2#40]
### Is your feature request related to a problem? Please describe.

Improve website and README.

### Describe the solution you'd like

- [ ] add a link to roadmap issues in README and website
- [ ] add the downloads stats to README. See https://github.com/autogenhub/autogen/issues/92
- [ ] change the readme of the autogenhub repo to direct to the new repo
- [ ] improve the discoverability of projects using AG2. See https://github.com/autogenhub/build-with-autogen/issues/6

**Comment by qingyun-wu** [comment]
Getting start page needs enhancement: https://ag2ai.github.io/ag2/docs/Getting-Started/
@skzhang1

**Comment by skzhang1** [comment]
> Getting start page needs enhancement: https://ag2ai.github.io/ag2/docs/Getting-Started/ @skzhang1

Any suggestions here?

**Comment by willhama** [comment]
I would like to help on this topic. The readme seems to not have a clear structure to follow. If we compare it to the old autogen project, it feels cluttered with information that is not needed. Stil,l I don't know exactly where to find the things I need to find in the documentation and the readme should be the initial starting point. Do you mind me suggesting a new readme? @sonichi @qingyun-wu @skzhang1

**Comment by sonichi** [comment]
@willhama thanks for your interest. @marklysze could you please onboard @willhama ? Also, feel free to reach out to me on Discord: sonichi

**Comment by sonichi** [comment]
How about starting from reviewing & revising #546 ?

**Comment by qingyun-wu** [comment]
Finished a round of improvement. Closing for now.
